# Generated by Django 3.2.5 on 2023-05-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('dur', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('cdate', models.DateField(auto_now=True)),
                ('trainer', models.CharField(max_length=25)),
            ],
        ),
    ]
