# Generated by Django 3.2.5 on 2023-06-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('portfolio', models.URLField(max_length=150)),
                ('pic', models.ImageField(upload_to='media/app1/images')),
                ('resume', models.FileField(upload_to='media/app1/files')),
                ('join_date', models.DateField(auto_now=True)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
        ),
    ]
